export const KEYS = [
  'action.back',
  'action.cancel',
  'action.done',
  'action.edit',
  'action.proceed',
  'action.stop',
  'auth.device.approval',
  'auth.hiveauth.instruction',
  'auth.hiveauth.openLink',
  'auth.oneClick.failed',
  'auth.oneClick.logging',
  'auth.oneClick.redirecting',
  'auth.username.label',
  'auth.username.placeholder',
  'modal.close',
  'modal.loading',
  'user.addAccount',
  'user.addAccountBtn',
  'user.avatarAlt',
  'user.loginAs',
  'user.logout',
  'user.removeAccount',
  'user.removeConfirm',
  'user.switch',
  'user.switchTo',
  'user.viewExplorer',
  'wallet.badge.popular',
  'wallet.badge.snap',
  'wallet.btcInstruction',
  'wallet.connect',
  'wallet.connectBitcoin',
  'wallet.connectEthereum',
  'wallet.connectInstruction',
  'wallet.ethInstruction',
  'wallet.helpLink',
  'wallet.provider.other',
  'wallet.provider.viewOnly',
  'wallet.sectionBitcoin',
  'wallet.sectionEthereum',
  'wallet.sectionHive',
  'wallet.selectType',
  'wallet.viewOnlyChain',
  'wallet.viewOnlyInvalid',
  'wallet.viewOnlyPlaceholder'
] as const

export type MessageId = (typeof KEYS)[number]

export type Catalog = Record<MessageId, string>
